// ═══════════════════════════════════════════════════════════════
// GAP-FILL CATALOGS — general desktop apps the core CATS data does
// not cover, for the six OS tabs that had no gap-fill companion:
// cachy / bazzite / arch / macos / ipados / android.
//
// windows / fedora / ubuntu keep their own standalone gapfill-*.html
// files (older, hand-built, already wired into their tabs).
//
// Item shape matches the core engine: {name, desc, cmd, type}.
// ═══════════════════════════════════════════════════════════════

// CachyOS and Arch share repositories, so they share this catalog.
const ARCH_FAMILY_CATS = [
  { id:'gf-web', icon:'🌐', title:'WEB BROWSERS & INTERNET',
    items:[
      {name:'Firefox', desc:'Default Mozilla browser', cmd:'sudo pacman -S --needed --noconfirm firefox', type:'pacman'},
      {name:'Chromium', desc:'Open-source base of Chrome', cmd:'sudo pacman -S --needed --noconfirm chromium', type:'pacman'},
      {name:'Google Chrome', desc:'Google browser (AUR)', cmd:'yay -S --needed --noconfirm google-chrome', type:'aur'},
      {name:'Brave Browser', desc:'Privacy-focused Chromium fork', cmd:'yay -S --needed --noconfirm brave-bin', type:'aur'},
      {name:'Vivaldi', desc:'Highly customizable browser', cmd:'sudo pacman -S --needed --noconfirm vivaldi', type:'pacman'},
      {name:'Tor Browser', desc:'Anonymized browsing', cmd:'sudo pacman -S --needed --noconfirm torbrowser-launcher', type:'pacman'},
      {name:'Thunderbird', desc:'Email client', cmd:'sudo pacman -S --needed --noconfirm thunderbird', type:'pacman'},
      {name:'Nextcloud Desktop', desc:'Sync client for Nextcloud', cmd:'sudo pacman -S --needed --noconfirm nextcloud-client', type:'pacman'},
      {name:'FileZilla', desc:'FTP/SFTP client', cmd:'sudo pacman -S --needed --noconfirm filezilla', type:'pacman'},
      {name:'qBittorrent', desc:'BitTorrent client', cmd:'sudo pacman -S --needed --noconfirm qbittorrent', type:'pacman'},
      {name:'Telegram Desktop', desc:'Telegram messenger', cmd:'sudo pacman -S --needed --noconfirm telegram-desktop', type:'pacman'},
      {name:'Discord', desc:'Chat/voice for communities', cmd:'sudo pacman -S --needed --noconfirm discord', type:'pacman'},
      {name:'Element', desc:'Matrix protocol client', cmd:'sudo pacman -S --needed --noconfirm element-desktop', type:'pacman'},
      {name:'Signal Desktop', desc:'Encrypted messenger', cmd:'sudo pacman -S --needed --noconfirm signal-desktop', type:'pacman'},
    ]},
  { id:'gf-office', icon:'📋', title:'OFFICE, PRODUCTIVITY & ORGANIZATION',
    items:[
      {name:'LibreOffice Fresh', desc:'Full office suite', cmd:'sudo pacman -S --needed --noconfirm libreoffice-fresh', type:'pacman'},
      {name:'OnlyOffice', desc:'MS Office-compatible suite', cmd:'flatpak install -y flathub org.onlyoffice.desktopeditors', type:'flatpak'},
      {name:'Obsidian', desc:'Markdown knowledge base', cmd:'sudo pacman -S --needed --noconfirm obsidian', type:'pacman'},
      {name:'Joplin', desc:'Encrypted note-taking', cmd:'flatpak install -y flathub net.cozic.joplin_desktop', type:'flatpak'},
      {name:'Calibre', desc:'Ebook management', cmd:'sudo pacman -S --needed --noconfirm calibre', type:'pacman'},
      {name:'Okular', desc:'KDE document viewer', cmd:'sudo pacman -S --needed --noconfirm okular', type:'pacman'},
      {name:'PDF Arranger', desc:'Merge/reorder/split PDF pages', cmd:'sudo pacman -S --needed --noconfirm pdfarranger', type:'pacman'},
      {name:'Planify', desc:'Task/todo manager', cmd:'flatpak install -y flathub io.github.alainm23.planify', type:'flatpak'},
      {name:'Freeplane', desc:'Mind mapping', cmd:'sudo pacman -S --needed --noconfirm freeplane', type:'pacman'},
      {name:'KeePassXC', desc:'Offline password manager', cmd:'sudo pacman -S --needed --noconfirm keepassxc', type:'pacman'},
    ]},
  { id:'gf-graphics', icon:'🎨', title:'GRAPHICS, DESIGN & PHOTOGRAPHY',
    items:[
      {name:'GIMP', desc:'Raster image editor', cmd:'sudo pacman -S --needed --noconfirm gimp', type:'pacman'},
      {name:'Inkscape', desc:'Vector graphics editor', cmd:'sudo pacman -S --needed --noconfirm inkscape', type:'pacman'},
      {name:'Krita', desc:'Digital painting', cmd:'sudo pacman -S --needed --noconfirm krita', type:'pacman'},
      {name:'Darktable', desc:'RAW photo workflow', cmd:'sudo pacman -S --needed --noconfirm darktable', type:'pacman'},
      {name:'RawTherapee', desc:'RAW photo processor', cmd:'sudo pacman -S --needed --noconfirm rawtherapee', type:'pacman'},
      {name:'digiKam', desc:'Pro photo management', cmd:'sudo pacman -S --needed --noconfirm digikam', type:'pacman'},
      {name:'Flameshot', desc:'Screenshot tool with annotation', cmd:'sudo pacman -S --needed --noconfirm flameshot', type:'pacman'},
      {name:'Pinta', desc:'Simple Paint.NET-style editor', cmd:'sudo pacman -S --needed --noconfirm pinta', type:'pacman'},
      {name:'FontForge', desc:'Font editor', cmd:'sudo pacman -S --needed --noconfirm fontforge', type:'pacman'},
      {name:'Shotwell', desc:'Photo manager/organizer', cmd:'sudo pacman -S --needed --noconfirm shotwell', type:'pacman'},
    ]},
  { id:'gf-media', icon:'🎬', title:'AUDIO, VIDEO & MEDIA',
    items:[
      {name:'VLC', desc:'Plays everything', cmd:'sudo pacman -S --needed --noconfirm vlc', type:'pacman'},
      {name:'mpv', desc:'Minimal GPU video player', cmd:'sudo pacman -S --needed --noconfirm mpv', type:'pacman'},
      {name:'Celluloid', desc:'GTK front-end for mpv', cmd:'sudo pacman -S --needed --noconfirm celluloid', type:'pacman'},
      {name:'Strawberry', desc:'Music library player', cmd:'sudo pacman -S --needed --noconfirm strawberry', type:'pacman'},
      {name:'Spotify', desc:'Music streaming (AUR)', cmd:'yay -S --needed --noconfirm spotify', type:'aur'},
      {name:'Shotcut', desc:'Video editor', cmd:'sudo pacman -S --needed --noconfirm shotcut', type:'pacman'},
      {name:'HandBrake', desc:'Video transcoder', cmd:'sudo pacman -S --needed --noconfirm handbrake', type:'pacman'},
      {name:'Asunder', desc:'CD ripper', cmd:'sudo pacman -S --needed --noconfirm asunder', type:'pacman'},
      {name:'Picard', desc:'MusicBrainz audio tagger', cmd:'sudo pacman -S --needed --noconfirm picard', type:'pacman'},
      {name:'SoundConverter', desc:'Batch audio format conversion', cmd:'sudo pacman -S --needed --noconfirm soundconverter', type:'pacman'},
    ]},
  { id:'gf-gaming', icon:'🎮', title:'GAMING & EMULATION',
    items:[
      {name:'Steam', desc:'Needs multilib enabled', cmd:'sudo pacman -S --needed --noconfirm steam', type:'pacman'},
      {name:'Lutris', desc:'Wine/Proton game manager', cmd:'sudo pacman -S --needed --noconfirm lutris', type:'pacman'},
      {name:'Bottles', desc:'Wine prefix manager', cmd:'flatpak install -y flathub com.usebottles.bottles', type:'flatpak'},
      {name:'Heroic Games Launcher', desc:'Epic / GOG / Amazon', cmd:'yay -S --needed --noconfirm heroic-games-launcher-bin', type:'aur'},
      {name:'ProtonUp-Qt', desc:'Install GE-Proton builds', cmd:'yay -S --needed --noconfirm protonup-qt', type:'aur'},
      {name:'RetroArch', desc:'Multi-system emulator frontend', cmd:'sudo pacman -S --needed --noconfirm retroarch retroarch-assets-xmb', type:'pacman'},
      {name:'Dolphin (GC/Wii)', desc:'Nintendo emulator', cmd:'sudo pacman -S --needed --noconfirm dolphin-emu', type:'pacman'},
      {name:'PCSX2 (PS2)', desc:'PlayStation 2 emulator', cmd:'sudo pacman -S --needed --noconfirm pcsx2', type:'pacman'},
      {name:'PPSSPP (PSP)', desc:'PSP emulator', cmd:'sudo pacman -S --needed --noconfirm ppsspp', type:'pacman'},
      {name:'ScummVM', desc:'Classic adventure engine', cmd:'sudo pacman -S --needed --noconfirm scummvm', type:'pacman'},
      {name:'Gamescope', desc:'Valve micro-compositor', cmd:'sudo pacman -S --needed --noconfirm gamescope', type:'pacman'},
      {name:'MangoHud', desc:'Performance overlay', cmd:'sudo pacman -S --needed --noconfirm mangohud lib32-mangohud', type:'pacman'},
    ]},
  { id:'gf-dev', icon:'💻', title:'DEV & CONTAINERS (SUBSET)',
    items:[
      {name:'Kitty', desc:'GPU-accelerated terminal', cmd:'sudo pacman -S --needed --noconfirm kitty', type:'pacman'},
      {name:'Alacritty', desc:'Minimal GPU terminal', cmd:'sudo pacman -S --needed --noconfirm alacritty', type:'pacman'},
      {name:'Meld', desc:'Visual diff/merge', cmd:'sudo pacman -S --needed --noconfirm meld', type:'pacman'},
      {name:'Lazygit', desc:'Terminal UI for git', cmd:'sudo pacman -S --needed --noconfirm lazygit', type:'pacman'},
      {name:'Podman', desc:'Rootless container engine', cmd:'sudo pacman -S --needed --noconfirm podman podman-compose', type:'pacman'},
      {name:'Distrobox', desc:'Run any distro on top of this one', cmd:'sudo pacman -S --needed --noconfirm distrobox', type:'pacman'},
      {name:'Virt-Manager + QEMU/KVM', desc:'Full VM stack', cmd:'sudo pacman -S --needed --noconfirm virt-manager qemu-full libvirt edk2-ovmf dnsmasq', type:'pacman'},
      {name:'DBeaver', desc:'Universal database client', cmd:'sudo pacman -S --needed --noconfirm dbeaver', type:'pacman'},
      {name:'Insomnia', desc:'REST/GraphQL client', cmd:'yay -S --needed --noconfirm insomnia-bin', type:'aur'},
      {name:'Zed', desc:'Fast collaborative editor', cmd:'sudo pacman -S --needed --noconfirm zed', type:'pacman'},
    ]},
  { id:'gf-sys', icon:'🛠️', title:'SYSTEM UTILITIES, TWEAKS & MANAGEMENT',
    items:[
      {name:'GParted', desc:'Partition editor', cmd:'sudo pacman -S --needed --noconfirm gparted', type:'pacman'},
      {name:'Timeshift', desc:'System restore points', cmd:'sudo pacman -S --needed --noconfirm timeshift', type:'pacman'},
      {name:'Snapper + snap-pac', desc:'Btrfs snapshots on every pacman run', cmd:'sudo pacman -S --needed --noconfirm snapper snap-pac', type:'pacman'},
      {name:'BleachBit', desc:'Disk cleaner', cmd:'sudo pacman -S --needed --noconfirm bleachbit', type:'pacman'},
      {name:'btop + htop', desc:'Resource monitors', cmd:'sudo pacman -S --needed --noconfirm btop htop', type:'pacman'},
      {name:'ncdu + duf', desc:'Disk usage explorers', cmd:'sudo pacman -S --needed --noconfirm ncdu duf', type:'pacman'},
      {name:'Syncthing', desc:'Peer-to-peer file sync', cmd:'sudo pacman -S --needed --noconfirm syncthing', type:'pacman'},
      {name:'Ventoy', desc:'Multi-ISO boot USB creator', cmd:'yay -S --needed --noconfirm ventoy-bin', type:'aur'},
      {name:'Fastfetch', desc:'System info readout', cmd:'sudo pacman -S --needed --noconfirm fastfetch', type:'pacman'},
      {name:'p7zip + unrar', desc:'Archive formats', cmd:'sudo pacman -S --needed --noconfirm p7zip unrar unzip zip', type:'pacman'},
      {name:'CUPS + printer drivers', desc:'Printing stack', cmd:'sudo pacman -S --needed --noconfirm cups system-config-printer', type:'pacman'},
      {name:'Solaar', desc:'Logitech Unifying device manager', cmd:'sudo pacman -S --needed --noconfirm solaar', type:'pacman'},
    ]},
];

const GAPFILL = {
  cachy: {
    label:'CACHYOS', color:'#6bc5f8', file:'tinker_cachy_gapfill.sh', kind:'bash',
    requires:'pacman', requiresMsg:'pacman not found — are you on CachyOS/Arch?',
    intro:'CachyOS ships the Arch repositories plus its own optimised ones, so everything here installs with <strong>pacman</strong>, <strong>yay</strong> (AUR) or <strong>Flatpak</strong>. AUR entries build from source — expect them to take longer.',
    cats:[
      { id:'gf-cachy', icon:'⚙️', title:'CACHYOS-SPECIFIC',
        items:[
          {name:'CachyOS Kernel Manager', desc:'Switch between the optimised CachyOS kernels', cmd:'sudo pacman -S --needed --noconfirm cachyos-kernel-manager', type:'pacman'},
          {name:'CachyOS Hello', desc:'Post-install welcome/tweak app', cmd:'sudo pacman -S --needed --noconfirm cachyos-hello', type:'pacman'},
          {name:'CachyOS Gaming Meta', desc:'Curated gaming package set', cmd:'sudo pacman -S --needed --noconfirm cachyos-gaming-meta', type:'pacman'},
          {name:'chwd (hardware detection)', desc:'CachyOS driver detection tool', cmd:'sudo pacman -S --needed --noconfirm chwd', type:'pacman'},
        ]},
      ...ARCH_FAMILY_CATS,
    ],
  },

  arch: {
    label:'ARCH LINUX', color:'#1793D1', file:'tinker_arch_gapfill.sh', kind:'bash',
    requires:'pacman', requiresMsg:'pacman not found — is this Arch?',
    intro:'Everything here installs with <strong>pacman</strong>, <strong>yay</strong> (AUR) or <strong>Flatpak</strong>. Enable <strong>multilib</strong> before Steam, and never partial-upgrade: run <strong>pacman -Syu</strong>, never <strong>-Sy package</strong>.',
    cats: ARCH_FAMILY_CATS,
  },

  bazzite: {
    label:'BAZZITE', color:'#a08fff', file:'tinker_bazzite_gapfill.sh', kind:'bash',
    requires:'flatpak', requiresMsg:'flatpak not found — is this Bazzite/an atomic Fedora?',
    intro:'Bazzite is <strong>immutable</strong>: Flatpak first, <strong>toolbox</strong> for CLI tools, and <strong>rpm-ostree</strong> layering only as a last resort — every layered package needs a reboot and slows future updates.',
    cats:[
      { id:'gf-web', icon:'🌐', title:'WEB BROWSERS & INTERNET',
        items:[
          {name:'Firefox', desc:'Pre-installed as a Flatpak on Bazzite', cmd:'flatpak install -y flathub org.mozilla.firefox', type:'flatpak'},
          {name:'Google Chrome', desc:'Google browser', cmd:'flatpak install -y flathub com.google.Chrome', type:'flatpak'},
          {name:'Brave Browser', desc:'Privacy-focused Chromium fork', cmd:'flatpak install -y flathub com.brave.Browser', type:'flatpak'},
          {name:'Chromium', desc:'Open-source base of Chrome', cmd:'flatpak install -y flathub org.chromium.Chromium', type:'flatpak'},
          {name:'Vivaldi', desc:'Highly customizable browser', cmd:'flatpak install -y flathub com.vivaldi.Vivaldi', type:'flatpak'},
          {name:'Tor Browser', desc:'Anonymized browsing', cmd:'flatpak install -y flathub org.torproject.torbrowser-launcher', type:'flatpak'},
          {name:'Thunderbird', desc:'Email client', cmd:'flatpak install -y flathub org.mozilla.Thunderbird', type:'flatpak'},
          {name:'Nextcloud Desktop', desc:'Sync client for Nextcloud', cmd:'flatpak install -y flathub com.nextcloud.desktopclient.nextcloud', type:'flatpak'},
          {name:'qBittorrent', desc:'BitTorrent client', cmd:'flatpak install -y flathub org.qbittorrent.qBittorrent', type:'flatpak'},
          {name:'Telegram Desktop', desc:'Telegram messenger', cmd:'flatpak install -y flathub org.telegram.desktop', type:'flatpak'},
          {name:'Discord', desc:'Chat/voice for communities', cmd:'flatpak install -y flathub com.discordapp.Discord', type:'flatpak'},
          {name:'Signal Desktop', desc:'Encrypted messenger', cmd:'flatpak install -y flathub org.signal.Signal', type:'flatpak'},
          {name:'Element', desc:'Matrix protocol client', cmd:'flatpak install -y flathub im.riot.Riot', type:'flatpak'},
        ]},
      { id:'gf-office', icon:'📋', title:'OFFICE, PRODUCTIVITY & ORGANIZATION',
        items:[
          {name:'LibreOffice', desc:'Full office suite', cmd:'flatpak install -y flathub org.libreoffice.LibreOffice', type:'flatpak'},
          {name:'OnlyOffice', desc:'MS Office-compatible suite', cmd:'flatpak install -y flathub org.onlyoffice.desktopeditors', type:'flatpak'},
          {name:'Obsidian', desc:'Markdown knowledge base', cmd:'flatpak install -y flathub md.obsidian.Obsidian', type:'flatpak'},
          {name:'Joplin', desc:'Encrypted note-taking', cmd:'flatpak install -y flathub net.cozic.joplin_desktop', type:'flatpak'},
          {name:'Calibre', desc:'Ebook management', cmd:'flatpak install -y flathub com.calibre_ebook.calibre', type:'flatpak'},
          {name:'Okular', desc:'Document viewer', cmd:'flatpak install -y flathub org.kde.okular', type:'flatpak'},
          {name:'PDF Arranger', desc:'Merge/reorder/split PDF pages', cmd:'flatpak install -y flathub com.github.jeromerobert.PdfArranger', type:'flatpak'},
          {name:'KeePassXC', desc:'Offline password manager', cmd:'flatpak install -y flathub org.keepassxc.KeePassXC', type:'flatpak'},
          {name:'Planify', desc:'Task/todo manager', cmd:'flatpak install -y flathub io.github.alainm23.planify', type:'flatpak'},
        ]},
      { id:'gf-graphics', icon:'🎨', title:'GRAPHICS, DESIGN & PHOTOGRAPHY',
        items:[
          {name:'GIMP', desc:'Raster image editor', cmd:'flatpak install -y flathub org.gimp.GIMP', type:'flatpak'},
          {name:'Inkscape', desc:'Vector graphics editor', cmd:'flatpak install -y flathub org.inkscape.Inkscape', type:'flatpak'},
          {name:'Krita', desc:'Digital painting', cmd:'flatpak install -y flathub org.kde.krita', type:'flatpak'},
          {name:'Blender', desc:'3D modeling/animation', cmd:'flatpak install -y flathub org.blender.Blender', type:'flatpak'},
          {name:'Darktable', desc:'RAW photo workflow', cmd:'flatpak install -y flathub org.darktable.Darktable', type:'flatpak'},
          {name:'RawTherapee', desc:'RAW photo processor', cmd:'flatpak install -y flathub com.rawtherapee.RawTherapee', type:'flatpak'},
          {name:'digiKam', desc:'Pro photo management', cmd:'flatpak install -y flathub org.kde.digikam', type:'flatpak'},
          {name:'Flameshot', desc:'Screenshot tool with annotation', cmd:'flatpak install -y flathub org.flameshot.Flameshot', type:'flatpak'},
          {name:'Pinta', desc:'Simple Paint.NET-style editor', cmd:'flatpak install -y flathub com.github.PintaProject.Pinta', type:'flatpak'},
        ]},
      { id:'gf-media', icon:'🎬', title:'AUDIO, VIDEO & MEDIA',
        items:[
          {name:'VLC', desc:'Plays everything', cmd:'flatpak install -y flathub org.videolan.VLC', type:'flatpak'},
          {name:'Celluloid', desc:'GTK front-end for mpv', cmd:'flatpak install -y flathub io.github.celluloid_player.Celluloid', type:'flatpak'},
          {name:'Strawberry', desc:'Music library player', cmd:'flatpak install -y flathub org.strawberrymusicplayer.strawberry', type:'flatpak'},
          {name:'Spotify', desc:'Music streaming', cmd:'flatpak install -y flathub com.spotify.Client', type:'flatpak'},
          {name:'Shotcut', desc:'Video editor', cmd:'flatpak install -y flathub org.shotcut.Shotcut', type:'flatpak'},
          {name:'HandBrake', desc:'Video transcoder', cmd:'flatpak install -y flathub fr.handbrake.ghb', type:'flatpak'},
          {name:'Picard', desc:'MusicBrainz audio tagger', cmd:'flatpak install -y flathub org.musicbrainz.Picard', type:'flatpak'},
          {name:'Audacity', desc:'Audio editor & recorder', cmd:'flatpak install -y flathub org.audacityteam.Audacity', type:'flatpak'},
        ]},
      { id:'gf-gaming', icon:'🎮', title:'GAMING & EMULATION (BAZZITE EXTRAS)',
        items:[
          {name:'Steam', desc:'Pre-installed on Bazzite — verify only', cmd:'flatpak list | grep -i steam || flatpak install -y flathub com.valvesoftware.Steam', type:'flatpak'},
          {name:'Heroic Games Launcher', desc:'Epic / GOG / Amazon', cmd:'flatpak install -y flathub com.heroicgameslauncher.hgl', type:'flatpak'},
          {name:'Bottles', desc:'Wine prefix manager', cmd:'flatpak install -y flathub com.usebottles.bottles', type:'flatpak'},
          {name:'ProtonUp-Qt', desc:'Install GE-Proton builds', cmd:'flatpak install -y flathub net.davidotek.pupgui2', type:'flatpak'},
          {name:'RetroArch', desc:'Multi-system emulator frontend', cmd:'flatpak install -y flathub org.libretro.RetroArch', type:'flatpak'},
          {name:'EmulationStation Desktop', desc:'Front-end for the whole emulator set', cmd:'flatpak install -y flathub org.es_de.frontend', type:'flatpak'},
          {name:'Dolphin (GC/Wii)', desc:'Nintendo emulator', cmd:'flatpak install -y flathub org.DolphinEmu.dolphin-emu', type:'flatpak'},
          {name:'PCSX2 (PS2)', desc:'PlayStation 2 emulator', cmd:'flatpak install -y flathub net.pcsx2.PCSX2', type:'flatpak'},
          {name:'RPCS3 (PS3)', desc:'PlayStation 3 emulator', cmd:'flatpak install -y flathub net.rpcs3.RPCS3', type:'flatpak'},
          {name:'PPSSPP (PSP)', desc:'PSP emulator', cmd:'flatpak install -y flathub org.ppsspp.PPSSPP', type:'flatpak'},
          {name:'Decky Loader', desc:'Steam Deck plugin loader — pre-installed', cmd:'# Pre-installed on Bazzite: hold ⋯ in Game Mode', type:'manual'},
        ]},
      { id:'gf-dev', icon:'💻', title:'DEV & CONTAINERS (TOOLBOX)',
        items:[
          {name:'VS Code', desc:'Editor as a Flatpak', cmd:'flatpak install -y flathub com.visualstudio.code', type:'flatpak'},
          {name:'Zed', desc:'Fast collaborative editor', cmd:'flatpak install -y flathub dev.zed.Zed', type:'flatpak'},
          {name:'Distrobox', desc:'Pre-installed on Bazzite — any distro in a box', cmd:'distrobox create --name arch --image archlinux:latest', type:'manual'},
          {name:'Toolbox: dev basics', desc:'gcc/git/make inside the tinker toolbox', cmd:'toolbox run --container tinker sudo dnf install -y gcc git make', type:'toolbox'},
          {name:'Toolbox: neovim', desc:'Editor inside the container', cmd:'toolbox run --container tinker sudo dnf install -y neovim', type:'toolbox'},
          {name:'Toolbox: lazygit', desc:'Terminal UI for git', cmd:'toolbox run --container tinker sudo dnf install -y lazygit', type:'toolbox'},
          {name:'Podman Desktop', desc:'Container GUI', cmd:'flatpak install -y flathub io.podman_desktop.PodmanDesktop', type:'flatpak'},
          {name:'DBeaver', desc:'Universal database client', cmd:'flatpak install -y flathub io.dbeaver.DBeaverCommunity', type:'flatpak'},
          {name:'Virt-Manager (layered)', desc:'rpm-ostree layer — needs a reboot', cmd:'rpm-ostree install virt-manager', type:'ostree'},
        ]},
      { id:'gf-sys', icon:'🛠️', title:'SYSTEM UTILITIES & TWEAKS',
        items:[
          {name:'Flatseal', desc:'Manage Flatpak permissions — essential here', cmd:'flatpak install -y flathub com.github.tchx84.Flatseal', type:'flatpak'},
          {name:'Warehouse', desc:'Flatpak manager GUI — inspect and clean apps', cmd:'flatpak install -y flathub io.github.flattool.Warehouse', type:'flatpak'},
          {name:'GNOME Disks', desc:'Disk management', cmd:'flatpak install -y flathub org.gnome.DiskUtility', type:'flatpak'},
          {name:'Mission Center', desc:'Resource monitor', cmd:'flatpak install -y flathub io.missioncenter.MissionCenter', type:'flatpak'},
          {name:'Syncthing (Flatpak)', desc:'Peer-to-peer file sync', cmd:'flatpak install -y flathub me.kozec.syncthingtk', type:'flatpak'},
          {name:'ufw + gufw (layered)', desc:'Firewall — rpm-ostree layer, needs reboot', cmd:'rpm-ostree install gufw', type:'ostree'},
          {name:'Ventoy (layered)', desc:'Multi-ISO boot USB creator', cmd:'rpm-ostree install ventoy', type:'ostree'},
          {name:'rpm-ostree status', desc:'See what you have layered and pinned', cmd:'rpm-ostree status', type:'manual'},
          {name:'ujust (Bazzite helpers)', desc:'Bazzite\'s own maintenance recipes', cmd:'ujust --choose', type:'manual'},
        ]},
    ],
  },

  macos: {
    label:'MACOS', color:'#A2AAAD', file:'tinker_macos_gapfill.sh', kind:'bash',
    requires:'brew', requiresMsg:'brew not found — install Homebrew first (see the macOS tab JUMPSTART).',
    intro:'Everything here installs with <strong>Homebrew</strong>. Formulae are CLI tools; casks are GUI apps and may need a Gatekeeper approval in System Settings → Privacy &amp; Security on first launch.',
    cats:[
      { id:'gf-web', icon:'🌐', title:'WEB BROWSERS & INTERNET',
        items:[
          {name:'Firefox', desc:'Mozilla browser', cmd:'brew install --cask firefox', type:'brew'},
          {name:'Google Chrome', desc:'Google browser', cmd:'brew install --cask google-chrome', type:'brew'},
          {name:'Brave Browser', desc:'Privacy-focused Chromium fork', cmd:'brew install --cask brave-browser', type:'brew'},
          {name:'Arc', desc:'Opinionated Chromium browser', cmd:'brew install --cask arc', type:'brew'},
          {name:'Tor Browser', desc:'Anonymized browsing', cmd:'brew install --cask tor-browser', type:'brew'},
          {name:'Thunderbird', desc:'Email client', cmd:'brew install --cask thunderbird', type:'brew'},
          {name:'Transmission', desc:'BitTorrent client', cmd:'brew install --cask transmission', type:'brew'},
          {name:'Cyberduck', desc:'FTP/SFTP/S3 client', cmd:'brew install --cask cyberduck', type:'brew'},
          {name:'Telegram', desc:'Telegram messenger', cmd:'brew install --cask telegram', type:'brew'},
          {name:'Discord', desc:'Chat/voice for communities', cmd:'brew install --cask discord', type:'brew'},
          {name:'Signal', desc:'Encrypted messenger', cmd:'brew install --cask signal', type:'brew'},
          {name:'Element', desc:'Matrix protocol client', cmd:'brew install --cask element', type:'brew'},
        ]},
      { id:'gf-office', icon:'📋', title:'OFFICE, PRODUCTIVITY & ORGANIZATION',
        items:[
          {name:'LibreOffice', desc:'Full office suite', cmd:'brew install --cask libreoffice', type:'brew'},
          {name:'OnlyOffice', desc:'MS Office-compatible suite', cmd:'brew install --cask onlyoffice', type:'brew'},
          {name:'Obsidian', desc:'Markdown knowledge base', cmd:'brew install --cask obsidian', type:'brew'},
          {name:'Joplin', desc:'Encrypted note-taking', cmd:'brew install --cask joplin', type:'brew'},
          {name:'Calibre', desc:'Ebook management', cmd:'brew install --cask calibre', type:'brew'},
          {name:'Skim', desc:'PDF reader/annotator', cmd:'brew install --cask skim', type:'brew'},
          {name:'KeePassXC', desc:'Offline password manager', cmd:'brew install --cask keepassxc', type:'brew'},
          {name:'Raycast', desc:'Spotlight replacement / launcher', cmd:'brew install --cask raycast', type:'brew'},
          {name:'Rectangle', desc:'Keyboard window management', cmd:'brew install --cask rectangle', type:'brew'},
          {name:'AltTab', desc:'Windows-style alt-tab switching', cmd:'brew install --cask alt-tab', type:'brew'},
        ]},
      { id:'gf-graphics', icon:'🎨', title:'GRAPHICS, DESIGN & PHOTOGRAPHY',
        items:[
          {name:'GIMP', desc:'Raster image editor', cmd:'brew install --cask gimp', type:'brew'},
          {name:'Inkscape', desc:'Vector graphics editor', cmd:'brew install --cask inkscape', type:'brew'},
          {name:'Krita', desc:'Digital painting', cmd:'brew install --cask krita', type:'brew'},
          {name:'Blender', desc:'3D modeling/animation', cmd:'brew install --cask blender', type:'brew'},
          {name:'Darktable', desc:'RAW photo workflow', cmd:'brew install --cask darktable', type:'brew'},
          {name:'RawTherapee', desc:'RAW photo processor', cmd:'brew install --cask rawtherapee', type:'brew'},
          {name:'ImageOptim', desc:'Lossless image compression', cmd:'brew install --cask imageoptim', type:'brew'},
          {name:'Figma', desc:'Interface design', cmd:'brew install --cask figma', type:'brew'},
          {name:'FontForge', desc:'Font editor', cmd:'brew install --cask fontforge', type:'brew'},
          {name:'ImageMagick', desc:'CLI image processing', cmd:'brew install imagemagick', type:'brew'},
        ]},
      { id:'gf-media', icon:'🎬', title:'AUDIO, VIDEO & MEDIA',
        items:[
          {name:'VLC', desc:'Plays everything', cmd:'brew install --cask vlc', type:'brew'},
          {name:'IINA', desc:'macOS-native mpv front-end', cmd:'brew install --cask iina', type:'brew'},
          {name:'Spotify', desc:'Music streaming', cmd:'brew install --cask spotify', type:'brew'},
          {name:'Doppler', desc:'Local music library player', cmd:'brew install --cask doppler', type:'brew'},
          {name:'HandBrake', desc:'Video transcoder', cmd:'brew install --cask handbrake', type:'brew'},
          {name:'Shotcut', desc:'Video editor', cmd:'brew install --cask shotcut', type:'brew'},
          {name:'Audacity', desc:'Audio editor & recorder', cmd:'brew install --cask audacity', type:'brew'},
          {name:'Picard', desc:'MusicBrainz audio tagger', cmd:'brew install --cask musicbrainz-picard', type:'brew'},
          {name:'yt-dlp + ffmpeg', desc:'CLI download + transcode stack', cmd:'brew install yt-dlp ffmpeg', type:'brew'},
          {name:'Loopback alternative: BlackHole', desc:'Virtual audio routing', cmd:'brew install --cask blackhole-2ch', type:'brew'},
        ]},
      { id:'gf-gaming', icon:'🎮', title:'GAMING & EMULATION',
        items:[
          {name:'Steam', desc:'PC gaming platform', cmd:'brew install --cask steam', type:'brew'},
          {name:'Whisky', desc:'Game Porting Toolkit front-end', cmd:'brew install --cask whisky', type:'brew'},
          {name:'CrossOver', desc:'Commercial Windows compat layer', cmd:'brew install --cask crossover', type:'brew'},
          {name:'OpenEmu', desc:'macOS-native multi-system emulator', cmd:'brew install --cask openemu', type:'brew'},
          {name:'RetroArch', desc:'Multi-system emulator frontend', cmd:'brew install --cask retroarch', type:'brew'},
          {name:'Dolphin (GC/Wii)', desc:'Nintendo emulator', cmd:'brew install --cask dolphin', type:'brew'},
          {name:'PPSSPP (PSP)', desc:'PSP emulator', cmd:'brew install --cask ppsspp', type:'brew'},
          {name:'DuckStation (PS1)', desc:'PlayStation 1 emulator', cmd:'brew install --cask duckstation', type:'brew'},
          {name:'ScummVM', desc:'Classic adventure engine', cmd:'brew install --cask scummvm', type:'brew'},
        ]},
      { id:'gf-dev', icon:'💻', title:'DEV & CONTAINERS (SUBSET)',
        items:[
          {name:'iTerm2', desc:'Terminal replacement', cmd:'brew install --cask iterm2', type:'brew'},
          {name:'Warp', desc:'Modern terminal', cmd:'brew install --cask warp', type:'brew'},
          {name:'Zed', desc:'Fast collaborative editor', cmd:'brew install --cask zed', type:'brew'},
          {name:'Sublime Text', desc:'Fast text editor', cmd:'brew install --cask sublime-text', type:'brew'},
          {name:'OrbStack', desc:'Fast Docker/Linux VM runtime', cmd:'brew install --cask orbstack', type:'brew'},
          {name:'UTM', desc:'QEMU-based VM manager for macOS', cmd:'brew install --cask utm', type:'brew'},
          {name:'DBeaver', desc:'Universal database client', cmd:'brew install --cask dbeaver-community', type:'brew'},
          {name:'Insomnia', desc:'REST/GraphQL client', cmd:'brew install --cask insomnia', type:'brew'},
          {name:'Lazygit + gh', desc:'Terminal git workflow', cmd:'brew install lazygit gh', type:'brew'},
          {name:'jq + yq + tree', desc:'Everyday shell helpers', cmd:'brew install jq yq tree', type:'brew'},
        ]},
      { id:'gf-sys', icon:'🛠️', title:'SYSTEM UTILITIES & TWEAKS',
        items:[
          {name:'The Unarchiver', desc:'Handles rar/7z/everything', cmd:'brew install --cask the-unarchiver', type:'brew'},
          {name:'AppCleaner', desc:'Removes apps and their leftovers', cmd:'brew install --cask appcleaner', type:'brew'},
          {name:'Stats', desc:'Menu-bar system monitor', cmd:'brew install --cask stats', type:'brew'},
          {name:'Hidden Bar', desc:'Menu-bar icon manager', cmd:'brew install --cask hiddenbar', type:'brew'},
          {name:'Balena Etcher', desc:'Write ISOs to USB', cmd:'brew install --cask balenaetcher', type:'brew'},
          {name:'Syncthing', desc:'Peer-to-peer file sync', cmd:'brew install syncthing', type:'brew'},
          {name:'Tailscale', desc:'Mesh VPN — cluster access', cmd:'brew install --cask tailscale', type:'brew'},
          {name:'mas', desc:'Mac App Store from the terminal', cmd:'brew install mas', type:'brew'},
          {name:'btop + htop', desc:'Resource monitors', cmd:'brew install btop htop', type:'brew'},
          {name:'ncdu + duf', desc:'Disk usage explorers', cmd:'brew install ncdu duf', type:'brew'},
        ]},
    ],
  },

  ipados: {
    label:'IPADOS', color:'#5E5CE6', file:'tinker_ipados_gapfill.txt', kind:'text',
    intro:'iPadOS has no package manager and no installer scripts — this list generates a <strong>checklist</strong> instead. App Store entries are tapped by hand; the shell lines run inside <strong>a-Shell</strong> or <strong>iSH</strong>.',
    cats:[
      { id:'gf-web', icon:'🌐', title:'BROWSERS & INTERNET',
        items:[
          {name:'Safari', desc:'Pre-installed — every other "browser" uses its engine', cmd:'# Built in', type:'manual'},
          {name:'Firefox', desc:'Mozilla shell over WebKit', cmd:'# App Store: Firefox', type:'manual'},
          {name:'Brave', desc:'Privacy-focused browser with ad blocking', cmd:'# App Store: Brave', type:'manual'},
          {name:'Onion Browser', desc:'Tor access on iPadOS', cmd:'# App Store: Onion Browser', type:'manual'},
          {name:'Documents by Readdle', desc:'File manager, downloader, SMB/FTP client', cmd:'# App Store: Documents', type:'manual'},
          {name:'Telegram', desc:'Telegram messenger', cmd:'# App Store: Telegram Messenger', type:'manual'},
          {name:'Signal', desc:'Encrypted messenger', cmd:'# App Store: Signal', type:'manual'},
          {name:'Element', desc:'Matrix protocol client', cmd:'# App Store: Element Messenger', type:'manual'},
        ]},
      { id:'gf-office', icon:'📋', title:'OFFICE & ORGANIZATION',
        items:[
          {name:'Pages / Numbers / Keynote', desc:'Free Apple office suite', cmd:'# App Store: Pages, Numbers, Keynote', type:'manual'},
          {name:'Microsoft 365', desc:'Word/Excel/PowerPoint — subscription for full editing', cmd:'# App Store: Microsoft 365', type:'manual'},
          {name:'Obsidian', desc:'Markdown knowledge base — syncs with desktop', cmd:'# App Store: Obsidian', type:'manual'},
          {name:'GoodNotes 6', desc:'Handwriting + PDF annotation', cmd:'# App Store: GoodNotes 6', type:'manual'},
          {name:'PDF Expert', desc:'PDF editing and signing', cmd:'# App Store: PDF Expert', type:'manual'},
          {name:'Things 3 / Reminders', desc:'Task management', cmd:'# App Store: Things 3 (paid) — Reminders is built in', type:'manual'},
          {name:'KeePassium', desc:'KeePassXC-compatible vault', cmd:'# App Store: KeePassium', type:'manual'},
          {name:'Calibre companion?', desc:'No native Calibre — use the built-in Books app or KyBook', cmd:'# No iPadOS Calibre build', type:'na'},
        ]},
      { id:'gf-graphics', icon:'🎨', title:'GRAPHICS & DESIGN',
        items:[
          {name:'Procreate', desc:'The flagship iPad raster painting app', cmd:'# App Store: Procreate (paid)', type:'manual'},
          {name:'Affinity Photo 2', desc:'Photoshop-class raster editing', cmd:'# App Store: Affinity Photo 2 (paid)', type:'manual'},
          {name:'Affinity Designer 2', desc:'Vector design', cmd:'# App Store: Affinity Designer 2 (paid)', type:'manual'},
          {name:'Vectornator / Linearity Curve', desc:'Free vector design', cmd:'# App Store: Linearity Curve', type:'manual'},
          {name:'Nomad Sculpt', desc:'3D sculpting', cmd:'# App Store: Nomad Sculpt (paid)', type:'manual'},
          {name:'Shapr3D', desc:'Parametric CAD for 3D printing', cmd:'# App Store: Shapr3D', type:'manual'},
          {name:'GIMP / Inkscape', desc:'No iPadOS builds exist — Affinity is the substitute', cmd:'# Not available on iPadOS', type:'na'},
          {name:'Pixelmator Pro', desc:'Native image editor', cmd:'# App Store: Pixelmator Pro', type:'manual'},
        ]},
      { id:'gf-media', icon:'🎬', title:'AUDIO, VIDEO & MEDIA',
        items:[
          {name:'VLC for Mobile', desc:'Plays everything', cmd:'# App Store: VLC for Mobile', type:'manual'},
          {name:'Infuse', desc:'Best Jellyfin/Plex front-end', cmd:'# App Store: Infuse', type:'manual'},
          {name:'LumaFusion', desc:'Pro multitrack video editing', cmd:'# App Store: LumaFusion (paid)', type:'manual'},
          {name:'GarageBand', desc:'Free Apple DAW', cmd:'# App Store: GarageBand', type:'manual'},
          {name:'AUM — Audio Mixer', desc:'AUv3 host/router', cmd:'# App Store: AUM (paid)', type:'manual'},
          {name:'Ferrite Recording Studio', desc:'Podcast/audio editing', cmd:'# App Store: Ferrite', type:'manual'},
          {name:'ffmpeg in a-Shell', desc:'Built into a-Shell — no install step', cmd:'ffmpeg -i input.mov -c:v h264 output.mp4', type:'manual'},
          {name:'yt-dlp in a-Shell', desc:'Python downloader inside the sandbox', cmd:'pip install yt-dlp', type:'pip'},
        ]},
      { id:'gf-dev', icon:'💻', title:'DEVELOPMENT',
        items:[
          {name:'Working Copy', desc:'Full git client', cmd:'# App Store: Working Copy', type:'manual'},
          {name:'Textastic', desc:'Code editor with SSH/SFTP', cmd:'# App Store: Textastic', type:'manual'},
          {name:'Runestone', desc:'Free open-source code editor', cmd:'# App Store: Runestone', type:'manual'},
          {name:'Swift Playgrounds', desc:'Build and ship real apps on-device', cmd:'# App Store: Swift Playgrounds', type:'manual'},
          {name:'Blink Shell', desc:'SSH/mosh — the real dev workflow on iPad', cmd:'# App Store: Blink Shell', type:'manual'},
          {name:'a-Shell python packages', desc:'Local Python tooling', cmd:'pip install requests httpx rich', type:'pip'},
          {name:'iSH base toolchain', desc:'Alpine packages inside iSH', cmd:'apk add git python3 py3-pip curl nano', type:'manual'},
          {name:'Docker / VS Code', desc:'Not possible on iPadOS — SSH to the LAN box instead', cmd:'# Sandbox forbids background daemons', type:'na'},
        ]},
      { id:'gf-sys', icon:'🛠️', title:'SYSTEM & REMOTE ACCESS',
        items:[
          {name:'Tailscale', desc:'Mesh VPN — reach the sovereign box anywhere', cmd:'# App Store: Tailscale', type:'manual'},
          {name:'Screens 5', desc:'VNC into the desktop machines', cmd:'# App Store: Screens 5 (paid)', type:'manual'},
          {name:'Jump Desktop', desc:'RDP/VNC alternative', cmd:'# App Store: Jump Desktop (paid)', type:'manual'},
          {name:'LocalSend', desc:'Sovereign LAN file transfer', cmd:'# App Store: LocalSend', type:'manual'},
          {name:'Secure ShellFish', desc:'SSH mounted into the Files app', cmd:'# App Store: Secure ShellFish', type:'manual'},
          {name:'Shortcuts automations', desc:'Built in — the glue for everything above', cmd:'# Shortcuts app → Automation', type:'manual'},
          {name:'SMB mount in Files', desc:'Mount the LAN box\'s shares natively', cmd:'# Files → ⋯ → Connect to Server → smb://<lan-ip>', type:'manual'},
        ]},
    ],
  },

  android: {
    label:'ANDROID / TERMUX', color:'#3DDC84', file:'tinker_android_gapfill.sh', kind:'bash',
    requires:'pkg', requiresMsg:'pkg not found — run this inside Termux (F-Droid build).',
    intro:'CLI packages install with <strong>pkg</strong> inside Termux; GUI apps come from <strong>F-Droid</strong> or the Play Store and are listed as manual steps — Android has no scriptable app installer without root.',
    cats:[
      { id:'gf-web', icon:'🌐', title:'BROWSERS & INTERNET',
        items:[
          {name:'Firefox', desc:'Real Gecko engine with extensions', cmd:'# F-Droid / Play Store: Firefox', type:'manual'},
          {name:'Brave', desc:'Privacy-focused browser with ad blocking', cmd:'# Play Store: Brave', type:'manual'},
          {name:'Mull', desc:'Hardened Firefox fork', cmd:'# F-Droid: Mull', type:'manual'},
          {name:'Tor Browser', desc:'Anonymized browsing', cmd:'# F-Droid / Play Store: Tor Browser', type:'manual'},
          {name:'Thunderbird for Android', desc:'Email client (formerly K-9 Mail)', cmd:'# F-Droid: Thunderbird', type:'manual'},
          {name:'Telegram', desc:'Telegram messenger', cmd:'# F-Droid / Play Store: Telegram', type:'manual'},
          {name:'Signal', desc:'Encrypted messenger', cmd:'# Play Store: Signal', type:'manual'},
          {name:'Element', desc:'Matrix protocol client', cmd:'# F-Droid: Element', type:'manual'},
          {name:'curl + wget (Termux)', desc:'CLI fetching', cmd:'pkg install -y curl wget', type:'termux'},
        ]},
      { id:'gf-office', icon:'📋', title:'OFFICE & ORGANIZATION',
        items:[
          {name:'Collabora Office', desc:'LibreOffice-based mobile suite', cmd:'# F-Droid / Play Store: Collabora Office', type:'manual'},
          {name:'Obsidian', desc:'Markdown knowledge base — syncs with desktop', cmd:'# Play Store: Obsidian', type:'manual'},
          {name:'Joplin', desc:'Encrypted note-taking', cmd:'# F-Droid: Joplin', type:'manual'},
          {name:'KeePassDX', desc:'Offline password manager', cmd:'# F-Droid: KeePassDX', type:'manual'},
          {name:'Tasks.org', desc:'Open-source task manager', cmd:'# F-Droid: Tasks.org', type:'manual'},
          {name:'Librera Reader', desc:'Ebook/PDF reader', cmd:'# F-Droid: Librera', type:'manual'},
          {name:'MuPDF / qpdf (Termux)', desc:'CLI PDF processing', cmd:'pkg install -y qpdf', type:'termux'},
          {name:'pandoc (Termux)', desc:'Document conversion in the shell', cmd:'pkg install -y pandoc', type:'termux'},
        ]},
      { id:'gf-graphics', icon:'🎨', title:'GRAPHICS & DESIGN',
        items:[
          {name:'Infinite Painter', desc:'Full-featured raster painting', cmd:'# Play Store: Infinite Painter', type:'manual'},
          {name:'ibis Paint X', desc:'Free painting app with brush engine', cmd:'# Play Store: ibis Paint X', type:'manual'},
          {name:'Krita / GIMP', desc:'No Android builds — the two above are the substitutes', cmd:'# Not available on Android', type:'na'},
          {name:'Photopea (web)', desc:'Photoshop-class editing in the browser', cmd:'# Browser: photopea.com — add to home screen', type:'manual'},
          {name:'Open Camera', desc:'Manual-control camera — raw capture', cmd:'# F-Droid: Open Camera', type:'manual'},
          {name:'ImageMagick (Termux)', desc:'CLI image processing', cmd:'pkg install -y imagemagick', type:'termux'},
          {name:'Simple Gallery Pro', desc:'Offline gallery with editing', cmd:'# F-Droid: Fossify Gallery', type:'manual'},
        ]},
      { id:'gf-media', icon:'🎬', title:'AUDIO, VIDEO & MEDIA',
        items:[
          {name:'VLC for Android', desc:'Plays everything', cmd:'# F-Droid / Play Store: VLC', type:'manual'},
          {name:'mpv-android', desc:'GPU media player', cmd:'# F-Droid: mpv-android', type:'manual'},
          {name:'NewPipe', desc:'Privacy-respecting YouTube front-end', cmd:'# F-Droid: NewPipe', type:'manual'},
          {name:'AntennaPod', desc:'Open-source podcast client', cmd:'# F-Droid: AntennaPod', type:'manual'},
          {name:'Vinyl / Fossify Music', desc:'Local music players', cmd:'# F-Droid: Fossify Music Player', type:'manual'},
          {name:'Jellyfin for Android', desc:'Client for the home media server', cmd:'# F-Droid / Play Store: Jellyfin', type:'manual'},
          {name:'ffmpeg (Termux)', desc:'CLI transcoding', cmd:'pkg install -y ffmpeg', type:'termux'},
          {name:'yt-dlp (Termux)', desc:'Downloader — writes to shared storage', cmd:'pip install yt-dlp', type:'pip'},
        ]},
      { id:'gf-gaming', icon:'🎮', title:'GAMING & EMULATION',
        items:[
          {name:'RetroArch', desc:'Multi-system emulator frontend', cmd:'# F-Droid / Play Store: RetroArch', type:'manual'},
          {name:'Dolphin (GC/Wii)', desc:'Nintendo emulator', cmd:'# Play Store: Dolphin Emulator', type:'manual'},
          {name:'PPSSPP (PSP)', desc:'PSP emulator', cmd:'# F-Droid / Play Store: PPSSPP', type:'manual'},
          {name:'DuckStation (PS1)', desc:'PlayStation 1 emulator', cmd:'# Play Store: DuckStation', type:'manual'},
          {name:'AetherSX2 / NetherSX2', desc:'PS2 emulation — sideload only now', cmd:'# No longer on the Play Store — sideload', type:'na'},
          {name:'Winlator', desc:'Windows/Wine on Android — sideload', cmd:'# GitHub: brunodev85/winlator', type:'manual'},
          {name:'Steam Link', desc:'Stream from the desktop over LAN', cmd:'# Play Store: Steam Link', type:'manual'},
          {name:'Moonlight', desc:'Low-latency PC game streaming', cmd:'# F-Droid / Play Store: Moonlight', type:'manual'},
        ]},
      { id:'gf-dev', icon:'💻', title:'DEV & TERMINAL',
        items:[
          {name:'Termux:API', desc:'Battery, clipboard, TTS, sensors from the shell', cmd:'pkg install -y termux-api', type:'termux'},
          {name:'Termux:Styling', desc:'Fonts + colour schemes', cmd:'# F-Droid: Termux:Styling', type:'manual'},
          {name:'Termux:Widget', desc:'Home-screen buttons for shell scripts', cmd:'# F-Droid: Termux:Widget', type:'manual'},
          {name:'Acode', desc:'GUI code editor that reads Termux storage', cmd:'# F-Droid / Play Store: Acode', type:'manual'},
          {name:'proot-distro', desc:'Real Debian/Ubuntu rootfs in Termux', cmd:'pkg install -y proot-distro', type:'termux'},
          {name:'openssh + mosh', desc:'Reach the sovereign box from the phone', cmd:'pkg install -y openssh mosh', type:'termux'},
          {name:'lazygit + gh', desc:'Terminal git workflow', cmd:'pkg install -y lazygit gh', type:'termux'},
          {name:'jq + ripgrep + fzf', desc:'Everyday shell helpers', cmd:'pkg install -y jq ripgrep fzf', type:'termux'},
        ]},
      { id:'gf-sys', icon:'🛠️', title:'SYSTEM & SYNC',
        items:[
          {name:'F-Droid', desc:'The open-source app store — install first', cmd:'# https://f-droid.org', type:'manual'},
          {name:'Obtainium', desc:'Installs apps straight from GitHub releases', cmd:'# F-Droid: Obtainium', type:'manual'},
          {name:'Syncthing-Fork', desc:'Peer-to-peer sync with the float', cmd:'# F-Droid: Syncthing-Fork', type:'manual'},
          {name:'Material Files', desc:'File manager with root/SMB support', cmd:'# F-Droid: Material Files', type:'manual'},
          {name:'Tailscale', desc:'Mesh VPN — joins the cluster', cmd:'# Play Store: Tailscale', type:'manual'},
          {name:'rclone (Termux)', desc:'Cloud sync from the shell', cmd:'pkg install -y rclone', type:'termux'},
          {name:'rsync + tar (Termux)', desc:'Backups to the LAN box', cmd:'pkg install -y rsync tar', type:'termux'},
          {name:'Termux:Boot', desc:'Run sshd/ollama at device boot', cmd:'# F-Droid: Termux:Boot', type:'manual'},
        ]},
    ],
  },
};
